@RiverBooks.Web_HostAddress = http://localhost:5162


###

GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json


###

@BookId=7ff39bbd-ac8d-4339-bcd0-f04fbe082c2b
GET {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "8ff39bbd-ac8d-4339-bcd0-f04fbe082c2b",
  "title": "There and back again",
  "author": "J.R.R. Tolkein",
  "price": 7.990000
}
